/* 1 - ETAPA */
SELECT DISTINCT DDA.CODPARC,
                DDA.NUMDOCTO,
                FIN.NUMNOTA,
                FIN.DESDOBRAMENTO,
                DDA.DTVENC,
                DDA.VALOR,
                FIN.VLRDESDOB,
                DDA.CODPARC
  FROM AD_INTDDA DDA
  JOIN TGFFIN FIN
    ON FIN.CODPARC = DDA.CODPARC
 WHERE DDA.DTVENC = FIN.DTVENC
   AND DDA.VALOR = ABS(FIN.VLRDESDOB)

/* 2 - ETAPA */

--ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS'
